server:
  port: 5001

spring:
  thymeleaf:
    enabled: false
  security:
    user:
      name: admin
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
